#include "maomi_learning.h"
#include "maomi_pet_presentation.h"

#include <cstdlib>
#include <iostream>

#define CHECK(x)                                      \
    do {                                              \
        if (!(x)) {                                   \
            std::cerr << __LINE__ << ": " #x << '\n'; \
            std::exit(1);                             \
        }                                             \
    } while (0)

class LifeStore : public maomi::LearningStore {
public:
    std::vector<uint8_t> save, books[2];
    bool fail = false;
    bool LoadState(std::vector<uint8_t>& out) override {
        out = save;
        return true;
    }
    bool SaveState(const std::vector<uint8_t>& data) override {
        if (fail)
            return false;
        save = data;
        return true;
    }
    bool LoadBook(int slot, std::vector<uint8_t>& out) override {
        out = books[slot];
        return true;
    }
    bool SaveBook(int slot, const std::vector<uint8_t>& data) override {
        books[slot] = data;
        return true;
    }
};

std::vector<uint8_t> Unhex(const std::string& hex) {
    std::vector<uint8_t> bytes;
    for (size_t i = 0; i < hex.size(); i += 2)
        bytes.push_back(static_cast<uint8_t>(std::stoul(hex.substr(i, 2), nullptr, 16)));
    return bytes;
}

int main() {
    // Golden fixture generated by the pre-upgrade engine: a real v1 save with an
    // unfinished two-word session, first answer rewarded, and its matching book.
    {
        LifeStore old;
        old.save = Unhex(
            "01004c4d0400000006004c656761637900d2496b0000000000d2496b0000000000d2496b00000000000000"
            "0000000000234c3501234c35010200000000000000502a2e08010000000200000006000300000064000000"
            "0000020001010001020205007374616d7005007072697a65020005007374616d70aed6f88c80234b6b0000"
            "0000234c3501234c35010105007072697a655372d14e0000000000000000000000000000000000c728310"
            "a");
        old.books[1] = Unhex(
            "01004c4d020005007374616d700700706f737461676505007072697a650600726577617264502a2e08");
        const auto legacy = old.save;
        maomi::LearningEngine migrated(old);
        const maomi::LearningTime now{1800000000, 20270115, 1, 15};
        CHECK(migrated.Load());
        CHECK(old.save == legacy);  // Reading does not mutate the original backup.
        CHECK(migrated.GetState().name == "Legacy" && migrated.GetState().coins == 2);
        CHECK(migrated.GetState().food == 6 && migrated.GetState().litter == 3);
        CHECK(migrated.GetState().birthday == 20270115 && migrated.GetState().question == 1);
        CHECK(migrated.GetLife(now).health == 100 && migrated.GetLife(now).energy == 100);
        CHECK(migrated.CurrentWord()->word == "prize");
        old.fail = true;
        CHECK(!migrated.Answer(1, 1, "correct", now).ok);
        CHECK(old.save == legacy && migrated.GetState().question == 1);
        old.fail = false;
        CHECK(migrated.Answer(1, 1, "correct", now).ok);
        CHECK(old.save[0] == 2 && migrated.GetState().coins == 14);
        maomi::LearningEngine reload(old);
        CHECK(reload.Load() && reload.GetState().coins == 14 && !reload.GetState().active);
        CHECK(reload.GetBook().size() == 2 && reload.GetState().history[0].stage == 1);
        old.save.back() ^= 1;
        maomi::LearningEngine corrupt(old);
        CHECK(!corrupt.Load());
        CHECK(corrupt.Care("doctor", now, 0).error == "storage_unavailable");
    }
    using maomi::PetHomeVisible;
    using maomi::PetPriority;
    CHECK(PetHomeVisible(kDeviceStateIdle, PetPriority::kIdle, false, false, false));
    CHECK(!PetHomeVisible(kDeviceStateIdle, PetPriority::kIdle, true, false, false));
    CHECK(!PetHomeVisible(kDeviceStateIdle, PetPriority::kIdle, false, true, false));
    CHECK(!PetHomeVisible(kDeviceStateIdle, PetPriority::kIdle, false, false, true));
    for (auto priority : {PetPriority::kCritical, PetPriority::kOfficial, PetPriority::kReminder,
                          PetPriority::kPower, PetPriority::kInteraction})
        CHECK(!PetHomeVisible(kDeviceStateIdle, priority, false, false, false));
    for (auto state : {kDeviceStateListening, kDeviceStateSpeaking, kDeviceStateConnecting,
                       kDeviceStateUpgrading})
        CHECK(!PetHomeVisible(state, PetPriority::kIdle, false, false, false));
    LifeStore store;
    maomi::LearningEngine e(store);
    maomi::LearningTime t{1800000000, 20270115, 1, 15};
    CHECK(e.Load());
    CHECK(e.Adopt("Mimi", t, 0).ok);
    CHECK(e.GetLife(t).health == 100);
    CHECK(e.Care("doctor", t, e.GetState().revision).error == "already_healthy");
    CHECK(e.Care("water", t, e.GetState().revision).error == "not_thirsty");
    CHECK(e.Care("supplies", t, e.GetState().revision).error == "already_stocked");
    CHECK(e.Care("sleep", t, e.GetState().revision).ok);
    CHECK(e.IsSleeping(t));
    auto later = t;
    later.epoch += 3600;
    later.hour = 13;
    CHECK(e.Observe(later).ok);
    CHECK(e.GetLife(later).hydration == 97);
    CHECK(e.Care("water", later, e.GetState().revision).ok);
    CHECK(e.GetLife(later).hydration == 100);
    CHECK(e.Care("wake", later, e.GetState().revision).ok);
    CHECK(!e.IsSleeping(later));
    CHECK(e.Import({{"stamp", "邮票"}, {"prize", "奖品"}}, later, e.GetState().revision).ok);
    CHECK(e.Start(false, later, e.GetState().revision).ok);
    CHECK(e.Care("sleep", later, e.GetState().revision).ok);
    CHECK(e.Answer(e.GetState().session, 0, "correct", later).error == "pet_sleeping");
    CHECK(e.Start(false, later, e.GetState().revision).ok);
    CHECK(!e.IsSleeping(later) && e.CurrentWord()->word == "stamp");
    CHECK(e.Answer(e.GetState().session, 0, "correct", later).ok);
    CHECK(e.Answer(e.GetState().session, 1, "correct", later).ok);
    CHECK(e.GetState().coins == 14);
    CHECK(e.Buy("ball", 1, later, e.GetState().revision).ok);
    CHECK(e.GetState().coins == 2);
    CHECK(e.Buy("ball", 1, later, e.GetState().revision).error == "already_owned");
    CHECK(e.Buy("scarf", 1, later, e.GetState().revision).error == "growth_locked");
    CHECK(e.Use("ball", later, e.GetState().revision).ok);
    CHECK(e.Use("ball", later, e.GetState().revision).error == "play_cooldown");
    CHECK(e.GetLife(later).play_days == 1);
    const auto before = store.save;
    store.fail = true;
    CHECK(e.Care("sleep", later, e.GetState().revision).error == "storage_write_failed");
    CHECK(store.save == before && !e.IsSleeping(later));
    store.fail = false;
    maomi::LearningEngine restored(store);
    CHECK(restored.Load());
    CHECK(restored.GetLife(later).owned == e.GetLife(later).owned);
    auto absent = later;
    absent.epoch += 30 * 86400;
    absent.date = 20270214;
    CHECK(restored.Observe(absent).ok);
    CHECK(restored.GetState().name == "Mimi");
    CHECK(restored.GetLife(absent).health >= 40 && restored.GetLife(absent).health < 60);
    CHECK(restored.Care("doctor", absent, restored.GetState().revision).ok);
    CHECK(restored.GetLife(absent).health == 100);
    CHECK(restored.Use("star_hat", absent, restored.GetState().revision).error == "not_owned");
    // Time rollback never restores hourly resource loss or reopens a daily claim.
    CHECK(restored.GetLife(t).hydration == restored.GetLife(absent).hydration);
    CHECK(restored.GetState().coins == 2);

    // Night sleep follows the local clock; an explicit wake lasts two hours.
    auto night = absent;
    night.hour = 22;
    CHECK(restored.IsSleeping(night));
    {
        LifeStore growth_store;
        maomi::LearningEngine cat(growth_store);
        CHECK(cat.Load());
        maomi::LearningTime day{1800000000, 20270201, 2, 1};
        CHECK(cat.Adopt("Grow", day, 0).ok);
        for (int i = 1; i <= 21; ++i) {
            day.epoch += 86400;
            ++day.date;
            ++day.day;
            CHECK(cat.Observe(day).ok);
            const auto supply = cat.Care("supplies", day, cat.GetState().revision);
            CHECK(supply.ok || supply.error == "already_stocked");
            CHECK(cat.Care("feed", day, cat.GetState().revision).ok);
            CHECK(cat.Care("feed", day, cat.GetState().revision).ok);
            CHECK(cat.Care("clean", day, cat.GetState().revision).ok);
            if (supply.ok) {
                CHECK(cat.Care("supplies", day, cat.GetState().revision).error ==
                      "supplies_claimed");
                auto rollback = day;
                rollback.date--;
                rollback.epoch -= 86400;
                CHECK(cat.Care("supplies", rollback, cat.GetState().revision).error ==
                      "supplies_claimed");
            }
            CHECK(cat.Care("pet", day, cat.GetState().revision).ok);
            CHECK(cat.GetLife(day).pet_days == uint32_t(i));
            CHECK(cat.GetState().care_days == uint32_t(i));
            // New meanings require learning again; rewards still obey the normal daily rule.
            CHECK(cat.Import({{"cat", std::to_string(i)}}, day, cat.GetState().revision).ok);
            CHECK(cat.Start(false, day, cat.GetState().revision).ok);
            CHECK(cat.Answer(cat.GetState().session, 0, "correct", day).ok);
        }
        CHECK(std::string(maomi::PetGrowth(cat.GetState().care_days)) == "adult");
        CHECK(std::string(maomi::PetPersonality(cat.GetLife(day))) == "gentle");
        CHECK(cat.Buy("star_hat", 2, day, cat.GetState().revision).error == "durable_quantity_one");
        const auto coins = cat.GetState().coins;
        growth_store.fail = true;
        CHECK(!cat.Buy("star_hat", 1, day, cat.GetState().revision).ok);
        CHECK(cat.GetState().coins == coins && cat.GetLife(day).owned == 0);
        growth_store.fail = false;
        CHECK(cat.Buy("star_hat", 1, day, cat.GetState().revision).ok);
        CHECK(cat.Use("star_hat", day, cat.GetState().revision).ok);
        CHECK(cat.Buy("cat_bed", 1, day, cat.GetState().revision).ok);
        CHECK(cat.Use("cat_bed", day, cat.GetState().revision).ok);
        maomi::LearningEngine reload(growth_store);
        CHECK(reload.Load());
        CHECK(reload.GetLife(day).outfit == 2 && reload.GetLife(day).room == 2);
        CHECK(reload.Use("no_outfit", day, reload.GetState().revision).ok);
        CHECK(reload.Use("default_room", day, reload.GetState().revision).ok);
        CHECK(reload.GetLife(day).outfit == 0 && reload.GetLife(day).room == 0);
        CHECK(reload.GetLife(day).owned != 0);
    }
    CHECK(restored.Care("wake", night, restored.GetState().revision).ok);
    CHECK(!restored.IsSleeping(night));
    night.epoch += 2 * 3600;
    night.hour = 0;
    CHECK(restored.IsSleeping(night));
    std::cout << "pet life contracts passed\n";
}
